apiVersion: v1
kind: ClusterResourceQuota
metadata:
  name: clusterquota-andrew
spec:
  quota: 
    hard:
      pods: "25"
      configmaps: "25"
      limits.cpu: "25"
      limits.memory: "40Gi"
      persistentvolumeclaims: "25"
      requests.cpu: "25"
      requests.memory: "6Gi"
      services: "25"
  selector:
    annotations: 
      openshift.io/requester: andrew
