apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: null
  name: core-resource-limits
spec:
  limits:
  - type: Pod
    max:
      cpu: "10"
      memory: 8Gi
    min:
      cpu: 50m
      memory: 100Mi
  - type: Container
    min:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: "10"
      memory: 8Gi
    default:
      cpu: 50m
      memory: 100Mi
    defaultRequest:
      cpu: 50m
      memory: 100Mi
    maxLimitRequestRatio:
      cpu: "200"
